In [ ]:
# Install AWS CLI if missing
!pip install awscli

# Install pandas and pyarrow if needed
!pip install pandas pyarrow

Collecting awscli
  Downloading awscli-1.44.40-py3-none-any.whl.metadata (11 kB)
Collecting botocore==1.42.50 (from awscli)
  Downloading botocore-1.42.50-py3-none-any.whl.metadata (5.9 kB)
Collecting docutils<=0.19,>=0.18.1 (from awscli)
  Downloading docutils-0.19-py3-none-any.whl.metadata (2.7 kB)
Collecting s3transfer<0.17.0,>=0.16.0 (from awscli)
  Downloading s3transfer-0.16.0-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: PyYAML<6.1,>=3.10 in /usr/local/lib/python3.12/dist-packages (from awscli) (6.0.3)
Collecting colorama<0.4.7,>=0.2.5 (from awscli)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting rsa<4.8,>=3.1.2 (from awscli)
  Downloading rsa-4.7.2-py3-none-any.whl.metadata (3.6 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from botocore==1.42.50->awscli)
  Downloading jmespath-1.1.0-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python3.12/dist-packages (from botocore==1.42.50->awscli) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /usr/local/lib/python3.12/dist-packages (from botocore==1.42.50->awscli) (2.5.0)
Requirement already satisfied: pyasn1>=0.1.3 in /usr/local/lib/python3.12/dist-packages (from rsa<4.8,>=3.1.2->awscli) (0.6.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3.0.0,>=2.1->botocore==1.42.50->awscli) (1.17.0)
Downloading awscli-1.44.40-py3-none-any.whl (4.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 72.3 MB/s eta 0:00:00
Downloading botocore-1.42.50-py3-none-any.whl (14.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.6/14.6 MB 68.9 MB/s eta 0:00:00
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Downloading docutils-0.19-py3-none-any.whl (570 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 570.5/570.5 kB 24.8 MB/s eta 0:00:00
Downloading rsa-4.7.2-py3-none-any.whl (34 kB)
Downloading s3transfer-0.16.0-py3-none-any.whl (86 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.8/86.8 kB 4.3 MB/s eta 0:00:00
Downloading jmespath-1.1.0-py3-none-any.whl (20 kB)
Installing collected packages: rsa, jmespath, docutils, colorama, botocore, s3transfer, awscli
  Attempting uninstall: rsa
    Found existing installation: rsa 4.9.1
    Uninstalling rsa-4.9.1:
      Successfully uninstalled rsa-4.9.1
  Attempting uninstall: docutils
    Found existing installation: docutils 0.21.2
    Uninstalling docutils-0.21.2:
      Successfully uninstalled docutils-0.21.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sphinx 8.2.3 requires docutils<0.22,>=0.20, but you have docutils 0.19 which is incompatible.
Successfully installed awscli-1.44.40 botocore-1.42.50 colorama-0.4.6 docutils-0.19 jmespath-1.1.0 rsa-4.7.2 s3transfer-0.16.0
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.12/dist-packages (18.1.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

In [ ]:
pd.set_option("display.max_colwidth", None)

In [ ]:
!aws s3 ls --no-sign-request s3://eotarchive/eot-index/table/eot-main/

                           PRE crawl=EOT-2004/
                           PRE crawl=EOT-2008/
                           PRE crawl=EOT-2012/
                           PRE crawl=EOT-2016/
                           PRE crawl=EOT-2020/

In [ ]:
# Show Parquet part files for EOT-2012
!aws s3 ls --no-sign-request s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/

2023-11-08 16:58:32  427456938 part-00000-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
2023-11-08 16:58:32  336915049 part-00001-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
2023-11-08 16:58:33  289150555 part-00002-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
2023-11-08 16:58:34  310154264 part-00003-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
2023-11-08 16:58:34  305666378 part-00004-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
2023-11-08 16:58:40  302693565 part-00005-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
2023-11-08 16:58:41  284224418 part-00006-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
2023-11-08 16:58:41  263959485 part-00007-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
2023-11-08 16:58:41  246432635 part-00008-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
2023-11-08 16:58:42  244658321 part-00009-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
2023-11-08 16:58:47  253612283 part-00010-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
2023-11-08 16:58:47  243506942 part-00011-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
2023-11-08 16:58:48  312784070 part-00012-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
2023-11-08 16:58:48  257238694 part-00013-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
2023-11-08 16:58:48  239351471 part-00014-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
2023-11-08 16:58:53  249553604 part-00015-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
2023-11-08 16:58:53  236468002 part-00016-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
2023-11-08 16:58:54  223765578 part-00017-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
2023-11-08 16:58:54  256176556 part-00018-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
2023-11-08 16:58:54  221597668 part-00019-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
2023-11-08 16:58:58  213442846 part-00020-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
2023-11-08 16:58:58  216525592 part-00021-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
2023-11-08 16:58:58  209383607 part-00022-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
2023-11-08 16:58:59  213240409 part-00023-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
2023-11-08 16:58:59  229780100 part-00024-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
2023-11-08 16:59:03  213403829 part-00025-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
2023-11-08 16:59:03  210136236 part-00026-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
2023-11-08 16:59:03  235139018 part-00027-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
2023-11-08 16:59:04  202479202 part-00028-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
2023-11-08 16:59:04  196131374 part-00029-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
2023-11-08 16:59:07  194952809 part-00030-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
2023-11-08 16:59:08  192882611 part-00031-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
2023-11-08 16:59:08  186378956 part-00032-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
2023-11-08 16:59:08  199101906 part-00033-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
2023-11-08 16:59:09  180410497 part-00034-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
2023-11-08 16:59:12  180235551 part-00035-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
2023-11-08 16:59:12  195785389 part-00036-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
2023-11-08 16:59:13  178805859 part-00037-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
2023-11-08 16:59:13  176068070 part-00038-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
2023-11-08 16:59:13  167576482 part-00039-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
2023-11-08 16:59:16  170670852 part-00040-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
2023-11-08 16:59:17  171766198 part-00041-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
2023-11-08 16:59:17  170818188 part-00042-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
2023-11-08 16:59:17  176726463 part-00043-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
2023-11-08 16:59:17  170873436 part-00044-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
2023-11-08 16:59:20  173215065 part-00045-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
2023-11-08 16:59:20  173380751 part-00046-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
2023-11-08 16:59:21  158921329 part-00047-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet

In [ ]:
!aws s3 ls --no-sign-request s3://eotarchive/crawl-data/EOT-2012/cdx.paths.gz

2022-04-06 18:33:28     696686 cdx.paths.gz

In [ ]:
!mkdir EOT-2012/parquet/cdx/

In [ ]:
!aws s3 cp --no-sign-request s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20120915074514-00001.cdxj.gz EOT-2012/parquet/cdx

download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20120915074514-00001.cdxj.gz to EOT-2012/parquet/cdx/EOT-2012-20120915074514-00001.cdxj.gz

In [ ]:
import gzip
import json
import pandas as pd

path_gzip_file = "/content/EOT-2012/parquet/cdx/EOT-2012-20120915074514-00001.cdxj.gz"

rows = []

with gzip.open(path_gzip_file, "rt", encoding="utf-8") as f:
    for line in f:
        try:
            key, ts, json_blob = line.strip().split(" ", 2)
            record = json.loads(json_blob)

            record["surtkey"] = key
            record["timestamp"] = ts

            rows.append(record)

        except Exception as e:
            print("Parse error:", e)

df = pd.DataFrame(rows)

In [ ]:
df.iloc[0]

url                           http://www.afcrossroads.com/communications/images/include_pic.jpg
mime                                                                                 image/jpeg
status                                                                                      200
digest                                                    sha1:Q3PRZVZH2Q2X7U3KJGXHAIF3J5QRX5YC
length                                                                                     3873
offset                                                                                136238859
filename         crawl-data/EOT-2012/segments/IA-000/warc/EOT-2012-20120915074514-00001.warc.gz
mime-detected                                                                        image/jpeg
puid                                                                                     fmt/44
surtkey                                 com,afcrossroads)/communications/images/include_pic.jpg
timestamp                                                                        20120915075049
charset                                                                                     NaN
languages                                                                                   NaN
Name: 0, dtype: object

In [ ]:
df.nunique()

url              21047
mime                40
status              10
digest           17197
length           10673
offset           21067
filename             1
mime-detected       26
puid                49
surtkey          20419
timestamp          737
charset              8
languages           74
dtype: int64

In [ ]:
path_gzip_file = "/content/EOT-2012/parquet/cdx/cdx.paths.gz"

df = pd.read_csv(
    path_gzip_file, compression="gzip", header=0, sep=",", quotechar='"'
)

FileNotFoundError: [Errno 2] No such file or directory: '/content/EOT-2012/parquet/cdx/cdx.paths.gz'

In [ ]:
import pandas as pd

# Load the downloaded Parquet file
df = pd.read_parquet("EOT-2012/parquet/subset/part-00047-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet")

# Show column names and types
# print(df.dtypes)

# Preview the first few rows
df.loc[0]

url_surtkey                                   gov,gpo)/fdsys/search/pagedetails.action?collapse=true&collectioncode=uscode&frompagedetails=true&granuleid=uscode-2010-title25-chap1-sec4&oldpath=title+25/chapter+1/sec.+4&packageid=uscode-2010-title25&searchpath=title+25/chapter+40
url                           http://www.gpo.gov/fdsys/search/pagedetails.action?collectionCode=USCODE&searchPath=Title+25%2FCHAPTER+40&granuleId=USCODE-2010-title25-chap1-sec4&packageId=USCODE-2010-title25&oldPath=Title+25%2FChapter+1%2FSec.+4&fromPageDetails=true&collapse=true
url_host_name                                                                                                                                                                                                                                                               www.gpo.gov
url_host_tld                                                                                                                                                                                                                                                                        gov
url_host_2nd_last_part                                                                                                                                                                                                                                                              gpo
url_host_3rd_last_part                                                                                                                                                                                                                                                              www
url_host_4th_last_part                                                                                                                                                                                                                                                             None
url_host_5th_last_part                                                                                                                                                                                                                                                             None
url_host_registry_suffix                                                                                                                                                                                                                                                            gov
url_host_registered_domain                                                                                                                                                                                                                                                      gpo.gov
url_host_private_suffix                                                                                                                                                                                                                                                             gov
url_host_private_domain                                                                                                                                                                                                                                                         gpo.gov
url_host_name_reversed                                                                                                                                                                                                                                                      gov.gpo.www
url_protocol                                                                                                                                                                                                                                                                       http
url_port                                                                                                                                                                                                                                                                            NaN
url_path                                                                                                                                                                                                                                               /fdsys/search/pagedetails.action
url_query                                                                        collectionCode=USCODE&searchPath=Title+25%2FCHAPTER+40&granuleId=USCODE-2010-title25-chap1-sec4&packageId=USCODE-2010-title25&oldPath=Title+25%2FChapter+1%2FSec.+4&fromPageDetails=true&collapse=true
fetch_time                                                                                                                                                                                                                                                          2012-12-04 23:10:43
fetch_status                                                                                                                                                                                                                                                                        200
content_digest                                                                                                                                                                                                                                         2LWR3D6Y626XDNLQSZ4CV4DGYRBLAL77
content_mime_type                                                                                                                                                                                                                                                             text/html
content_mime_detected                                                                                                                                                                                                                                                         text/html
content_charset                                                                                                                                                                                                                                                              ISO-8859-1
content_languages                                                                                                                                                                                                                                                                   eng
content_puid                                                                                                                                                                                                                                                                    fmt/102
warc_filename                                                                                                                                                      crawl-data/EOT-2012/segments/UNT-003/warc/UNT-20121204231022001-24438-14030~libharvest2.library.unt.edu~8443.warc.gz
warc_record_offset                                                                                                                                                                                                                                                               638078
warc_record_length                                                                                                                                                                                                                                                                11634
warc_segment                                                                                                                                                                                                                                                                    UNT-003
crawl                                                                                                                                                                                                                                                                          EOT-2012
subset                                                                                                                                                                                                                                                                             warc
Name: 0, dtype: object

In [ ]:
!mkdir -p EOT-2012/parquet/subset/

In [ ]:
!aws s3 cp --no-sign-request s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00001-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet EOT-2012/parquet/subset/

download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00001-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/subset/part-00001-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet

In [ ]:
import pandas as pd

# Load the downloaded Parquet file
df = pd.read_parquet("EOT-2012/parquet/subset/part-00001-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet")

# Show column names and types
# print(df.dtypes)

# Preview the first few rows
df.nunique()

url_surtkey                   2808582
url                           2839383
url_host_name                    3297
url_host_tld                        4
url_host_2nd_last_part           1266
url_host_3rd_last_part           1670
url_host_4th_last_part            130
url_host_5th_last_part             18
url_host_registry_suffix            4
url_host_registered_domain       1266
url_host_private_suffix             8
url_host_private_domain          1704
url_host_name_reversed           3295
url_protocol                        3
url_port                            2
url_path                      1336476
url_query                     1325328
fetch_time                    2378741
fetch_status                       23
content_digest                2466267
content_mime_type                 105
content_mime_detected              57
content_charset                    21
content_languages                4617
content_puid                       91
warc_filename                   39106
warc_record_offset            3707574
warc_record_length             252240
warc_segment                       10
crawl                               1
subset                              1
dtype: int64

In [ ]:
import duckdb
import pandas as pd

In [ ]:
df = duckdb.sql("SELECT * FROM 'EOT-2012/parquet/subset/part-00047-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet' LIMIT 5").df()

In [ ]:
pd.DataFrame(df.columns, columns=["Column Name"])

                   Column Name
0                  url_surtkey
1                          url
2                url_host_name
3                 url_host_tld
4       url_host_2nd_last_part
5       url_host_3rd_last_part
6       url_host_4th_last_part
7       url_host_5th_last_part
8     url_host_registry_suffix
9   url_host_registered_domain
10     url_host_private_suffix
11     url_host_private_domain
12      url_host_name_reversed
13                url_protocol
14                    url_port
15                    url_path
16                   url_query
17                  fetch_time
18                fetch_status
19              content_digest
20           content_mime_type
21       content_mime_detected
22             content_charset
23           content_languages
24                content_puid
25               warc_filename
26          warc_record_offset
27          warc_record_length
28                warc_segment
29                       crawl
30                      subset

In [ ]:
duckdb.sql("""
    SELECT url_surtkey, fetch_status
    FROM 'EOT-2012/parquet/subset/part-00047-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet'
    WHERE fetch_status = 404
    LIMIT 5
""").df()

                                                 url  fetch_status
0  http://www.gpo.gov/fdsys/search/pagedetails.ac...           404
1  http://www.gpo.gov/fdsys/search/pagedetails.ac...           404
2  http://www.gpo.gov/fdsys/search/pagedetails.ac...           404
3  http://www.gpo.gov/fdsys/search/pagedetails.ac...           404
4  http://www.gpo.gov/fdsys/search/pagedetails.ac...           404

In [ ]:
!mkdir -p EOT-2012/parquet/full/

In [ ]:
!aws s3 sync --no-sign-request s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/ EOT-2012/parquet/full/

download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00003-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00003-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00002-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00002-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00001-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00001-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00004-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00004-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00008-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00008-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00000-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00000-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00006-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00006-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00007-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00007-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00005-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00005-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00011-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00011-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00009-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00009-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00010-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00010-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00015-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00015-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00013-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00013-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00014-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00014-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00012-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00012-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00016-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00016-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00019-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00019-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00017-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00017-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00018-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00018-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00021-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00021-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00023-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00023-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00020-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00020-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00022-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00022-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00025-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00025-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00026-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00026-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00028-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00028-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00024-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00024-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00027-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00027-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00029-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00029-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00031-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00031-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00032-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00032-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00033-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00033-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00034-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00034-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00030-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00030-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00035-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00035-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00036-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00036-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00037-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00037-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00038-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00038-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00039-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00039-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00040-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00040-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00041-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00041-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00042-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00042-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00044-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00044-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00043-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00043-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00047-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00047-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00045-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00045-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet
download: s3://eotarchive/eot-index/table/eot-main/crawl=EOT-2012/part-00046-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet to EOT-2012/parquet/full/part-00046-9a26f426-026b-4ca3-8e28-cbae857489be-c000.gz.parquet

In [ ]:
duckdb.sql("""
    CREATE VIEW eot_2012 AS
    SELECT *
    FROM '/content/EOT-2012/parquet/full/**/*.gz.parquet'
""")

In [ ]:
duckdb.sql("""
    SELECT *
    FROM eot_2012
    WHERE fetch_status = 404
    LIMIT 5
""").df()

,url_surtkey,url,url_host_name,url_host_tld,url_host_2nd_last_part,url_host_3rd_last_part,url_host_4th_last_part,url_host_5th_last_part,url_host_registry_suffix,url_host_registered_domain,...,content_mime_detected,content_charset,content_languages,content_puid,warc_filename,warc_record_offset,warc_record_length,warc_segment,crawl,subset
0,"com,youtube)/embed/ttp:/www.youtube.com/v/e1ppg105qkg",http://www.youtube.com/embed/ttp://www.youtube.com/v/e1PPg105Qkg,www.youtube.com,com,youtube,www,None,None,com,youtube.com,...,text/html,ascii,eng,fmt/471,crawl-data/EOT-2012/segments/IA-000/warc/EOT-2012-20120921164802214-01885-26126~wbgrp-crawl002.us.archive.org~8443.warc.gz,877256753,688,IA-000,EOT-2012,warc
1,"com,youtube)/embed/ttp:/www.youtube.com/v/e1ppg105qkg",http://www.youtube.com/embed/ttp://www.youtube.com/v/e1PPg105Qkg,www.youtube.com,com,youtube,www,None,None,com,youtube.com,...,text/html,ascii,eng,fmt/471,crawl-data/EOT-2012/segments/IA-000/warc/EOT-2012-20121009231250245-01145-23849~wbgrp-crawl002.us.archive.org~8443.warc.gz,348478341,691,IA-000,EOT-2012,warc
2,"com,youtube)/embed/ttp:/www.youtube.com/v/e1ppg105qkg",http://www.youtube.com/embed/ttp://www.youtube.com/v/e1PPg105Qkg,www.youtube.com,com,youtube,www,None,None,com,youtube.com,...,text/html,ascii,eng,fmt/471,crawl-data/EOT-2012/segments/IA-000/warc/EOT-2012-20121017093350314-00658-18439~wbgrp-crawl007.us.archive.org~8443.warc.gz,540914785,690,IA-000,EOT-2012,warc
3,"com,youtube)/embed/ttp:/www.youtube.com/v/e1ppg105qkg",http://www.youtube.com/embed/ttp://www.youtube.com/v/e1PPg105Qkg,www.youtube.com,com,youtube,www,None,None,com,youtube.com,...,text/html,ascii,eng,fmt/471,crawl-data/EOT-2012/segments/LOC-000/warc/LOC-EOT2012-001-20121108084543664-00227-15895~wbgrp-crawl012.us.archive.org~8443.warc.gz,902020843,689,LOC-000,EOT-2012,warc
4,"com,youtube)/embed/ttp:/www.youtube.com/v/e1ppg105qkg",http://www.youtube.com/embed/ttp://www.youtube.com/v/e1PPg105Qkg,www.youtube.com,com,youtube,www,None,None,com,youtube.com,...,text/html,ascii,eng,fmt/471,crawl-data/EOT-2012/segments/IA-000/warc/EOT-2012-20130215200307899-00640-10476~wbgrp-crawl013.us.archive.org~8443.warc.gz,516945292,685,IA-000,EOT-2012,warc

In [ ]:
duckdb.sql("""
    SELECT
        url_host_2nd_last_part,
        COUNT(*) AS url_count
    FROM '/content/EOT-2012/parquet/full/**/*.gz.parquet'
    GROUP BY url_host_2nd_last_part
    ORDER BY url_count DESC
""").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

       url_host_2nd_last_part  url_count
0                       house   36112972
1                      senate    9967319
2                         loc    7593918
3                    facebook    7510625
4                    dvidshub    5613295
...                       ...        ...
170105                   what          1
170106          univ-provence          1
170107                   wonb          1
170108                   wpat          1
170109                hamster          1

[170110 rows x 2 columns]

Warning: total number of rows (170110) exceeds max_rows (20000). Limiting to first (20000) rows.

In [ ]:
duckdb.sql("""
    SELECT
        url_host_private_suffix,
        COUNT(*) AS url_count
    FROM '/content/EOT-2012/parquet/full/**/*.gz.parquet'
    GROUP BY url_host_private_suffix
    ORDER BY url_count DESC
""").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

                       url_host_private_suffix  url_count
0                                          gov  109889349
1                                          com   45830183
2                                          mil   16320040
3                                          net    9155981
4                                          org    5718069
...                                        ...        ...
1086   ec2-50-17-84-46.compute-1.amazonaws.com          1
1087  ec2-72-44-63-165.compute-1.amazonaws.com          1
1088  ec2-75-101-197-7.compute-1.amazonaws.com          1
1089                                    no.com          1
1090                                    elk.pl          1

[1091 rows x 2 columns]

## Stream all .cdxj into parquet and then into duckdb

In [ ]:
!mkdir EOT-2012/converted/

In [ ]:
!aws s3 cp \
  --no-sign-request \
  --recursive \
  --exclude "*" \
  --include "*.cdxj.gz" \
  s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/ \
  EOT-2012/cdx/

Streaming output truncated to the last 5000 lines.
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007081959839-00461-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007081959839-00461-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007082105231-00463-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007082105231-00463-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007083029722-00467-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007083029722-00467-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007081257359-00459-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007081257359-00459-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007083634729-00470-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007083634729-00470-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007082709942-00464-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007082709942-00464-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007082742273-00465-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007082742273-00465-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007083944215-00472-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007083944215-00472-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007082009268-00462-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007082009268-00462-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007083958071-00473-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007083958071-00473-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007084947386-00478-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007084947386-00478-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007083823652-00471-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007083823652-00471-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007083243543-00468-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007083243543-00468-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007084619105-00476-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007084619105-00476-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007083320099-00469-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007083320099-00469-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007084312681-00474-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007084312681-00474-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007084639846-00477-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007084639846-00477-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007084545434-00475-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007084545434-00475-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007090246941-00486-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007090246941-00486-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007085438129-00481-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007085438129-00481-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007085245942-00480-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007085245942-00480-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007085110776-00479-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007085110776-00479-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007085947356-00484-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007085947356-00484-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007085925544-00483-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007085925544-00483-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007090801701-00487-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007090801701-00487-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007091056584-00490-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007091056584-00490-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007090152127-00485-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007090152127-00485-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007091047535-00489-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007091047535-00489-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007090805669-00488-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007090805669-00488-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007085516354-00482-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007085516354-00482-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007091758350-00493-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007091758350-00493-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007091407468-00491-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007091407468-00491-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007091824692-00494-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007091824692-00494-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007092439681-00498-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007092439681-00498-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007092138510-00496-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007092138510-00496-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007091444734-00492-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007091444734-00492-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007093031603-00501-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007093031603-00501-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007092643207-00499-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007092643207-00499-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007093152393-00503-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007093152393-00503-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007093037305-00502-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007093037305-00502-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007093608452-00505-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007093608452-00505-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007093444802-00504-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007093444802-00504-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007093635240-00506-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007093635240-00506-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007092810783-00500-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007092810783-00500-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007094110172-00508-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007094110172-00508-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007094300459-00509-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007094300459-00509-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007093911803-00507-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007093911803-00507-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007094959860-00513-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007094959860-00513-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007094717203-00511-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007094717203-00511-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007092055901-00495-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007092055901-00495-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007094932439-00512-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007094932439-00512-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007095053211-00514-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007095053211-00514-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007095806244-00516-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007095806244-00516-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007095840604-00517-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007095840604-00517-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007094525926-00510-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007094525926-00510-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007095524739-00515-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007095524739-00515-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007100026678-00518-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007100026678-00518-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007100714381-00521-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007100714381-00521-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007100630026-00520-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007100630026-00520-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007100353476-00519-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007100353476-00519-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007100759192-00522-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007100759192-00522-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007101419467-00524-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007101419467-00524-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007101524001-00525-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007101524001-00525-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007101246631-00523-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007101246631-00523-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007101604235-00526-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007101604235-00526-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007102228035-00529-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007102228035-00529-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007102146465-00528-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007102146465-00528-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007102020192-00527-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007102020192-00527-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007102314654-00530-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007102314654-00530-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007092322360-00497-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007092322360-00497-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007103534851-00535-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007103534851-00535-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007102959782-00533-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007102959782-00533-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007103726777-00537-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007103726777-00537-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007102900462-00532-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007102900462-00532-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007103649672-00536-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007103649672-00536-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007104310511-00540-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007104310511-00540-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007104222793-00539-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007104222793-00539-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007103810709-00538-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007103810709-00538-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007103039199-00534-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007103039199-00534-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007104953480-00543-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007104953480-00543-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz
download: s3://eotarchive/crawl-data/EOT-2012/segments/IA-000/cdx/EOT-2012-20121007104444104-00541-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz to EOT-2012/cdx/EOT-2012-20121007104444104-00541-23849~wbgrp-crawl002.us.archive.org~8443.cdxj.gz

In [ ]:
#

In [ ]:
import os, glob, gzip, json
import pyarrow as pa
import pyarrow.parquet as pq
from tqdm.auto import tqdm

paths = sorted(glob.glob("/content/EOT-2012/cdx/*.cdxj.gz"))
out_dir = "/content/EOT-2012/converted"
os.makedirs(out_dir, exist_ok=True)

# Choose the columns you want to keep (add/remove as needed)
COLUMNS = [
    "url", "mime", "status", "digest", "length", "offset", "filename",
    "mime-detected", "puid", "charset", "languages",
    "surtkey", "timestamp"
]

BATCH_SIZE = 50_000

for path in tqdm(paths, desc="Converting shards"):
    out = os.path.basename(path).replace(".cdxj.gz", ".parquet")
    out_path = os.path.join(out_dir, out)

    writer = None
    batch = []

    def normalize(rec):
        # ensure all columns exist
        return {k: rec.get(k) for k in COLUMNS}

    with gzip.open(path, "rt", encoding="utf-8") as f:
        for line in f:
            try:
                key, ts, json_blob = line.strip().split(" ", 2)
                rec = json.loads(json_blob)
                rec["surtkey"] = key
                rec["timestamp"] = ts
                batch.append(normalize(rec))
            except:
                continue

            if len(batch) >= BATCH_SIZE:
                table = pa.Table.from_pylist(batch)
                if writer is None:
                    writer = pq.ParquetWriter(
                        out_path,
                        table.schema,
                        compression="zstd",
                        use_dictionary=True
                    )
                writer.write_table(table)
                batch.clear()

    if batch:
        table = pa.Table.from_pylist(batch)
        if writer is None:
            writer = pq.ParquetWriter(
                out_path,
                table.schema,
                compression="zstd",
                use_dictionary=True
            )
        writer.write_table(table)

    if writer is not None:
        writer.close()

Converting shards:   0%|          | 0/10000 [00:00<?, ?it/s]

In [ ]:
import duckdb, os
con = duckdb.connect()  # or duckdb.connect("/content/eot.duckdb")
con.execute(f"PRAGMA threads={os.cpu_count() or 4};")
con.execute("PRAGMA enable_progress_bar;")

In [ ]:
# only read url column to speed things up...
con.execute("""
CREATE OR REPLACE TABLE eot_hosts AS
SELECT
  lower(regexp_extract(url, '^[a-z]+://([^/?#:]+)', 1)) AS host
FROM parquet_scan('/content/EOT-2012/converted/*.parquet');
""")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [ ]:
con.sql("SELECT COUNT(*) FROM eot_hosts").show()
con.sql("SELECT * FROM eot_hosts LIMIT 5").show()

┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│     48681429 │
└──────────────┘

┌──────────────────────┐
│         host         │
│       varchar        │
├──────────────────────┤
│ www.afcrossroads.com │
│ www.afcrossroads.com │
│ www.afcrossroads.com │
│ www.afcrossroads.com │
│ www.afcrossroads.com │
└──────────────────────┘

In [ ]:
#use ends_with which si faster than regex
con.sql("""
WITH labeled AS (
  SELECT
    host,
    CASE
      WHEN host='usda.gov' OR ends_with(host, '.usda.gov') THEN 'usda.gov'
      WHEN host='commerce.gov' OR ends_with(host, '.commerce.gov') THEN 'commerce.gov'
      WHEN host='defense.gov' OR ends_with(host, '.defense.gov') THEN 'defense.gov'
      WHEN host='ed.gov' OR ends_with(host, '.ed.gov') THEN 'ed.gov'
      WHEN host='energy.gov' OR ends_with(host, '.energy.gov') THEN 'energy.gov'
      WHEN host='hhs.gov' OR ends_with(host, '.hhs.gov') THEN 'hhs.gov'
      WHEN host='dhs.gov' OR ends_with(host, '.dhs.gov') THEN 'dhs.gov'
      WHEN host='hud.gov' OR ends_with(host, '.hud.gov') THEN 'hud.gov'
      WHEN host='doi.gov' OR ends_with(host, '.doi.gov') THEN 'doi.gov'
      WHEN host='justice.gov' OR ends_with(host, '.justice.gov') THEN 'justice.gov'
      WHEN host='dol.gov' OR ends_with(host, '.dol.gov') THEN 'dol.gov'
    END AS base_domain
  FROM eot_hosts
)
SELECT
  base_domain,
  host,
  COUNT(*) AS captures
FROM labeled
WHERE base_domain IS NOT NULL
GROUP BY base_domain, host
ORDER BY base_domain, captures DESC;
""").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

       base_domain                           host  captures
0     commerce.gov         2001-2009.commerce.gov     63769
1     commerce.gov               www.commerce.gov     47720
2     commerce.gov         selectusa.commerce.gov      3544
3     commerce.gov          recovery.commerce.gov      1036
4     commerce.gov                hr.commerce.gov       932
...            ...                            ...       ...
1127      usda.gov              agcensus.usda.gov         2
1128      usda.gov      pubsearch.arsnet.usda.gov         1
1129      usda.gov  google.search.csrees.usda.gov         1
1130      usda.gov                d2.nal.usda.gov         1
1131      usda.gov               offices.usda.gov         1

[1132 rows x 3 columns]

In [ ]:

con.sql("""
CREATE OR REPLACE VIEW eot_2012 AS
SELECT *
FROM read_parquet('/content/EOT-2012/converted/*.parquet');
""")

In [ ]:
con.sql("SELECT * FROM eot_2012 LIMIT 5").df()

,url,mime,status,digest,length,offset,filename,mime-detected,puid,charset,languages,surtkey,timestamp
0,http://www.afcrossroads.com/disclaimer.cfm?loc...,text/html,302,sha1:BSLFTGW4QCBGHGLKFKMYJLUBHTEI3Q5B,511,747376311,crawl-data/EOT-2012/segments/IA-000/warc/EOT-2...,text/plain,None,ascii,None,"com,afcrossroads)/disclaimer.cfm?faqid=290&loc...",20120915075744
1,http://www.afcrossroads.com/disclaimer.cfm?loc...,text/html,302,sha1:BSLFTGW4QCBGHGLKFKMYJLUBHTEI3Q5B,484,570737348,crawl-data/EOT-2012/segments/IA-000/warc/EOT-2...,text/plain,None,ascii,None,"com,afcrossroads)/disclaimer.cfm?location=http...",20120915075542
2,http://www.afcrossroads.com/disclaimer.cfm?loc...,text/html,302,sha1:BSLFTGW4QCBGHGLKFKMYJLUBHTEI3Q5B,447,455688148,crawl-data/EOT-2012/segments/IA-000/warc/EOT-2...,text/plain,None,ascii,None,"com,afcrossroads)/disclaimer.cfm?location=http...",20120915075408
3,http://www.afcrossroads.com/disclaimer.cfm?loc...,text/html,302,sha1:BSLFTGW4QCBGHGLKFKMYJLUBHTEI3Q5B,500,722233435,crawl-data/EOT-2012/segments/IA-000/warc/EOT-2...,text/plain,None,ascii,None,"com,afcrossroads)/disclaimer.cfm?location=http...",20120915075723
4,http://www.afcrossroads.com/disclaimer.cfm?loc...,text/html,302,sha1:BSLFTGW4QCBGHGLKFKMYJLUBHTEI3Q5B,478,681360811,crawl-data/EOT-2012/segments/IA-000/warc/EOT-2...,text/plain,None,ascii,None,"com,afcrossroads)/disclaimer.cfm?location=http...",20120915075655

In [ ]:
con.sql("SELECT COUNT(*) FROM eot_2012").show()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│     48681429 │
└──────────────┘

In [ ]:
con.sql("""
SELECT COUNT(*)
FROM eot_2012
WHERE lower(url) LIKE '%justice.gov%';
""").show()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│        64687 │
└──────────────┘

In [ ]:
con.sql("""
WITH hosts AS (
  SELECT
    lower(regexp_extract(url, '^[a-z]+://([^/?#:]+)', 1)) AS host
  FROM eot_2012
),
labeled AS (
  SELECT
    host,
    CASE
      WHEN host = 'usda.gov' OR host LIKE '%.usda.gov' THEN 'usda.gov'
      WHEN host = 'commerce.gov' OR host LIKE '%.commerce.gov' THEN 'commerce.gov'
      WHEN host = 'defense.gov' OR host LIKE '%.defense.gov' THEN 'defense.gov'
      WHEN host = 'ed.gov' OR host LIKE '%.ed.gov' THEN 'ed.gov'
      WHEN host = 'energy.gov' OR host LIKE '%.energy.gov' THEN 'energy.gov'
      WHEN host = 'hhs.gov' OR host LIKE '%.hhs.gov' THEN 'hhs.gov'
      WHEN host = 'dhs.gov' OR host LIKE '%.dhs.gov' THEN 'dhs.gov'
      WHEN host = 'hud.gov' OR host LIKE '%.hud.gov' THEN 'hud.gov'
      WHEN host = 'doi.gov' OR host LIKE '%.doi.gov' THEN 'doi.gov'
      WHEN host = 'justice.gov' OR host LIKE '%.justice.gov' THEN 'justice.gov'
      WHEN host = 'dol.gov' OR host LIKE '%.dol.gov' THEN 'dol.gov'
    END AS base_domain
  FROM hosts
)
SELECT
  base_domain,
  host,
  COUNT(*) AS captures
FROM labeled
WHERE base_domain IS NOT NULL
GROUP BY base_domain, host
ORDER BY base_domain, captures DESC;
""").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

       base_domain                           host  captures
0     commerce.gov         2001-2009.commerce.gov     63769
1     commerce.gov               www.commerce.gov     47720
2     commerce.gov         selectusa.commerce.gov      3544
3     commerce.gov          recovery.commerce.gov      1036
4     commerce.gov                hr.commerce.gov       932
...            ...                            ...       ...
1127      usda.gov       techprs.sc.egov.usda.gov         2
1128      usda.gov                d2.nal.usda.gov         1
1129      usda.gov               offices.usda.gov         1
1130      usda.gov      pubsearch.arsnet.usda.gov         1
1131      usda.gov  google.search.csrees.usda.gov         1

[1132 rows x 3 columns]

In [ ]:
con.sql("""CREATE TABLE eot_paths AS
SELECT
  lower(regexp_extract(url,'^[a-z]+://([^/]+)',1)) AS host,
  regexp_extract(url,'^[a-z]+://[^/]+(/[^?#]*)',1) AS path
FROM eot_2012;""")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [ ]:
con.sql("""
SELECT
  host,
  COALESCE(NULLIF(list_extract(string_split(trim(path, '/'), '/'), 1), ''), '(root)') AS path1,
  COUNT(*) AS captures
FROM eot_paths
WHERE host = 'commerce.gov' OR ends_with(host, '.commerce.gov')
GROUP BY host, path1
ORDER BY captures DESC;
""").df()

                        host             path1  captures
0     2001-2009.commerce.gov               opa     50926
1           www.commerce.gov              blog     15799
2           www.commerce.gov              news      8311
3           www.commerce.gov             sites      7642
4     2001-2009.commerce.gov          NewsRoom      7258
..                       ...               ...       ...
356         www.commerce.gov    evans_bio.html         1
357   selectusa.commerce.gov  %E2%80%9Dhttp%3A         1
358  acetool.my.commerce.gov              misc         1
359  acetool.my.commerce.gov              news         1
360  acetool.my.commerce.gov  About%20Commerce         1

[361 rows x 3 columns]

In [ ]:
con.sql("""
WITH labeled AS (
  SELECT
    host,
    path,
    CASE
      WHEN host='usda.gov' OR ends_with(host,'.usda.gov') THEN 'usda.gov'
      WHEN host='commerce.gov' OR ends_with(host,'.commerce.gov') THEN 'commerce.gov'
      WHEN host='defense.gov' OR ends_with(host,'.defense.gov') THEN 'defense.gov'
      WHEN host='ed.gov' OR ends_with(host,'.ed.gov') THEN 'ed.gov'
      WHEN host='energy.gov' OR ends_with(host,'.energy.gov') THEN 'energy.gov'
      WHEN host='hhs.gov' OR ends_with(host,'.hhs.gov') THEN 'hhs.gov'
      WHEN host='dhs.gov' OR ends_with(host,'.dhs.gov') THEN 'dhs.gov'
      WHEN host='hud.gov' OR ends_with(host,'.hud.gov') THEN 'hud.gov'
      WHEN host='doi.gov' OR ends_with(host,'.doi.gov') THEN 'doi.gov'
      WHEN host='justice.gov' OR ends_with(host,'.justice.gov') THEN 'justice.gov'
      WHEN host='dol.gov' OR ends_with(host,'.dol.gov') THEN 'dol.gov'
    END AS base_domain
  FROM eot_paths
)
SELECT
  base_domain,
  host,
  COALESCE(NULLIF(list_extract(string_split(trim(path, '/'), '/'), 1), ''), '(root)') AS path1,
  COUNT(*) AS captures
FROM labeled
WHERE base_domain IS NOT NULL
GROUP BY base_domain, host, path1
ORDER BY base_domain, host, captures DESC;
""").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

        base_domain                    host            path1  captures
0      commerce.gov  2001-2009.commerce.gov              opa     50926
1      commerce.gov  2001-2009.commerce.gov         NewsRoom      7258
2      commerce.gov  2001-2009.commerce.gov                s      4144
3      commerce.gov  2001-2009.commerce.gov         Services       539
4      commerce.gov  2001-2009.commerce.gov         graphics       227
...             ...                     ...              ...       ...
26082      usda.gov  www3.wcc.nrcs.usda.gov  reportGenerator        31
26083      usda.gov  www3.wcc.nrcs.usda.gov       robots.txt         4
26084      usda.gov  www3.wcc.nrcs.usda.gov       siteimages         2
26085      usda.gov  www3.wcc.nrcs.usda.gov          contact         1
26086      usda.gov  www3.wcc.nrcs.usda.gov           (root)         1

[26087 rows x 4 columns]

In [ ]:
con.execute("""
CREATE OR REPLACE TABLE eot_host_path2 AS
SELECT
  CASE
    WHEN host='usda.gov' OR ends_with(host,'.usda.gov') THEN 'usda.gov'
    WHEN host='commerce.gov' OR ends_with(host,'.commerce.gov') THEN 'commerce.gov'
    WHEN host='defense.gov' OR ends_with(host,'.defense.gov') THEN 'defense.gov'
    WHEN host='ed.gov' OR ends_with(host,'.ed.gov') THEN 'ed.gov'
    WHEN host='energy.gov' OR ends_with(host,'.energy.gov') THEN 'energy.gov'
    WHEN host='hhs.gov' OR ends_with(host,'.hhs.gov') THEN 'hhs.gov'
    WHEN host='dhs.gov' OR ends_with(host,'.dhs.gov') THEN 'dhs.gov'
    WHEN host='hud.gov' OR ends_with(host,'.hud.gov') THEN 'hud.gov'
    WHEN host='doi.gov' OR ends_with(host,'.doi.gov') THEN 'doi.gov'
    WHEN host='justice.gov' OR ends_with(host,'.justice.gov') THEN 'justice.gov'
    WHEN host='dol.gov' OR ends_with(host,'.dol.gov') THEN 'dol.gov'
  END AS base_domain,

  host,

  CASE
    WHEN path IS NULL OR path='' OR path='/' THEN '(root)'
    ELSE array_to_string(
      list_slice(string_split(trim(path,'/'),'/'), 1, 2),
      '/'
    )
  END AS path2

FROM eot_paths
WHERE
  host='usda.gov' OR ends_with(host,'.usda.gov')
  OR host='commerce.gov' OR ends_with(host,'.commerce.gov')
  OR host='defense.gov' OR ends_with(host,'.defense.gov')
  OR host='ed.gov' OR ends_with(host,'.ed.gov')
  OR host='energy.gov' OR ends_with(host,'.energy.gov')
  OR host='hhs.gov' OR ends_with(host,'.hhs.gov')
  OR host='dhs.gov' OR ends_with(host,'.dhs.gov')
  OR host='hud.gov' OR ends_with(host,'.hud.gov')
  OR host='doi.gov' OR ends_with(host,'.doi.gov')
  OR host='justice.gov' OR ends_with(host,'.justice.gov')
  OR host='dol.gov' OR ends_with(host,'.dol.gov');
""")
con.execute("CREATE INDEX IF NOT EXISTS idx_host_path2 ON eot_host_path2(host);")
con.execute("CREATE INDEX IF NOT EXISTS idx_base_domain ON eot_host_path2(base_domain);")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [ ]:
con.sql("""
SELECT base_domain, host, path2, COUNT(*) AS captures
FROM eot_host_path2
GROUP BY base_domain, host, path2
ORDER BY base_domain, host, captures DESC;
""").df()

,base_domain,host,path2,captures
0,commerce.gov,2001-2009.commerce.gov,opa/photo,50870
1,commerce.gov,2001-2009.commerce.gov,s/groups,4102
2,commerce.gov,2001-2009.commerce.gov,NewsRoom/PressReleases_FactSheets,2810
3,commerce.gov,2001-2009.commerce.gov,NewsRoom/TopNews,2197
4,commerce.gov,2001-2009.commerce.gov,NewsRoom/SecretarySpeeches,1268
...,...,...,...,...
119626,usda.gov,www3.wcc.nrcs.usda.gov,nwcc/dscan.js,1
119627,usda.gov,www3.wcc.nrcs.usda.gov,contact/db-message.html,1
119628,usda.gov,www3.wcc.nrcs.usda.gov,siteimages/413.jpg,1
119629,usda.gov,www3.wcc.nrcs.usda.gov,nwcc/dscan.css,1
119630,usda.gov,www3.wcc.nrcs.usda.gov,(root),1

Warning: total number of rows (119631) exceeds max_rows (20000). Limiting to first (20000) rows.